### ISSUE TITLE
Can't save to Camera Roll on Android

### ISSUE THREAD

**Issue by talyh** [olokobayusuf/NatShare-API#54]
When using `NatShare.SaveToCameraRoll(path)`, the Android build is able to save to local storage (I can see several recordings at android/data/<app.id>), but it's not transferring it into CameraRoll.

Looking at the ADB log, I see: 
2019-05-31 13:32:02.794 13791-13813/com.Armor2020.ProtoLocalStorage E/Unity: NatShare Error: Failed to save media to camera roll
    java.io.FileNotFoundException: /storage/emulated/0/DCIM/recording_2019_05_31_13_32_01_650.mp4 (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at com.yusufolokoba.natshare.NatShare.copyFile(NatShare.java:163)
        at com.yusufolokoba.natshare.NatShare.saveMediaToCameraRoll(NatShare.java:124)
        at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
        at com.unity3d.player.ReflectionHelper.a(Unknown Source:0)
        at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source:77)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy9.onRecording(Unknown Source)
        at com.yusufolokoba.natcorder.MP4Recorder$4$1.run(MP4Recorder.java:199)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

Looking at the forum I saw someone had an issue with DCIM/Camera folder not existing. I double checked and the folder is there, but no data related to the videos being recorded from my app.

Also, same build on iOS works fine.

This is using NatShare 1.3, Pixel 2, Android v9.

**Comment by olokobayusuf** [comment]
This seems to be related to #44. I'll be focusing on it in #49

**Comment by hoggMan** [comment]
Did you check your write permission in player settings? Changing from "internal" to "external(SDcard)" worked for me to resolve this

**Comment by kndol** [comment]
This code helps you:
```
#if UNITY_ANDROID
				if (!Permission.HasUserAuthorizedPermission(Permission.ExternalStorageWrite))
				{
					Permission.RequestUserPermission(Permission.ExternalStorageWrite);
				}
#endif

```

**Comment by talyh** [comment]
Sorry for the delay in commenting back here.
@hoggMan - Thanks for the recommendation to change the player settings writing. It definitely helped.
@kndol  - That code didn't help nor hurt. It didn't request the permission, but also it didn't prevent if from working when combined with @hoggMan recommendation.

Now, the video is saved to Camera Roll. However, the video is always saved as a black screen, despite the preview properly capturing the camera. I'll do some more research to try and figure out whether it's a NatCorder/NatShare/usage issue and open a separate one if needed.

**Comment by olokobayusuf** [comment]
> Now, the video is saved to Camera Roll. However, the video is always saved as a black screen, despite the preview properly capturing the camera. I'll do some more research to try and figure out whether it's a NatCorder/NatShare/usage issue and open a separate one if needed.

I presume you are referring to the thumbnail. Check your version of NatCorder; make sure you are using the latest version. This was an issue a long time ago; it has been implicitly fixed.

**Comment by SteveRPR** [comment]
In case someone comes upon this issue still as I did, despite having all the permissions set my AndroidManifest was still not checking for permissions on app launch:

`<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false" />`

Changing android:value="true" to "false" fixed the issue for me.
